name: Android CI

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version'
        required: true
        default: '1.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'keystore.jks'
          fileDir: '/home/runner/work/number_listenup/number_listenup/app/keystore/'
          encodedString: ${{ secrets.KEYSTORE }}
      - name: Build Bundle
        run: ./gradlew app:bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Rename Artifact
        run: mv app/build/outputs/bundle/release/app-release.aab app/build/outputs/bundle/release/number_listenup_${{ github.event.inputs.version }}.aab
      - name: Upload Bundle
        uses: actions/upload-artifact@v3.1.2
        with:
          name: number_listenup_bundle
          path: app/build/outputs/bundle/release/number_listenup_${{ github.event.inputs.version }}.aab
      # Build and sign APK ("-x test" argument is used to skip tests)
      - name: Build APK
        run: ./gradlew :app:assembleRelease -x test
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      # Show information about the APK's signing certificates
      - name: Verify Signature
        run: $ANDROID_SDK_ROOT/build-tools/33.0.1/apksigner verify --print-certs app/build/outputs/apk/release/number_listenup_${{ github.event.inputs.version }}.apk
# Save the APK after the Build job is complete to publish it as a Github release in the next job
      - name: Upload APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: number_listenup_apk
          path: app/build/outputs/apk/release/number_listenup_${{ github.event.inputs.version }}.apk
  release:
    name: release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: number_listenup_apk
      - name: Download Bundle from build
        uses: actions/download-artifact@v1
        with:
          name: number_listenup_bundle
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: 
            /home/runner/work/number_listenup/number_listenup/number_listenup_bundle/number_listenup_${{ github.event.inputs.version }}.apk
            /home/runner/work/number_listenup/number_listenup/number_listenup_bundle/number_listenup_${{ github.event.inputs.version }}.aab
